import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:archive/archive.dart';
import 'package:vehicle_poster/auction_excel_export.dart';
import 'package:vehicle_poster/auction_vehicle.dart';
import 'package:vehicle_poster/vehicle_import.dart';

AuctionVehicleEntry _entry(int id, AuctionVehicle vehicle) =>
    AuctionVehicleEntry(
      id: id,
      vehicle: vehicle,
      createdAt: DateTime.utc(2026, 9, 20),
      updatedAt: DateTime.utc(2026, 9, 20),
    );

void main() {
  test('imports XLSX files with title rows before the table header', () async {
    final bytes = AuctionExcelExporter.export([
      _entry(
        1,
        const AuctionVehicle(
          number: '2',
          vin: 'JTDKN3DU0A0231040',
          vehicleType: 'Prius',
          year: '2010',
          color: 'White',
          priceUsd: '6000',
        ),
      ),
    ], date: DateTime.utc(2026, 9, 20));

    final rows = await VehicleListImporter.fromBytes('auction.xlsx', bytes);

    expect(rows, hasLength(1));
    expect(rows.single.number, '2');
    expect(rows.single.vin, 'JTDKN3DU0A0231040');
    expect(rows.single.title, '2010');
    expect(rows.single.model, 'Prius');
    expect(rows.single.color, 'White');
    expect(rows.single.price, '6000');
  });

  test(
    'selects the worksheet with headers and accepts common header names',
    () async {
      final archive = Archive()
        ..add(
          ArchiveFile.string(
            'xl/worksheets/sheet1.xml',
            _worksheet([
              ['Report generated by Excel'],
            ]),
          ),
        )
        ..add(
          ArchiveFile.string(
            'xl/worksheets/sheet2.xml',
            _worksheet([
              [
                'Vehicle No',
                'Vehicle Identification Number',
                'Vehicle Description',
                'Year',
                'Exterior Color',
                'Sale Price',
              ],
              [
                '7',
                '1N4AL3AP7JC123456',
                '2018 Nissan Altima',
                '2018',
                'Blue',
                '12000',
              ],
            ], prefixed: true),
          ),
        );

      final rows = await VehicleListImporter.fromBytes(
        'vehicles.xlsx',
        ZipEncoder().encodeBytes(archive),
      );

      expect(rows, hasLength(1));
      expect(rows.single.number, '7');
      expect(rows.single.vin, '1N4AL3AP7JC123456');
      expect(rows.single.title, '2018');
      expect(rows.single.model, '2018 Nissan Altima');
      expect(rows.single.color, 'Blue');
      expect(rows.single.price, '12000');
    },
  );
  test(
    'legacy Vehicle Type and Model columns keep the original poster text',
    () async {
      final rows = await VehicleListImporter.fromBytes(
        'vehicles.csv',
        utf8.encode('''
No.,Vehicle Type,Model,Color
2,CROLLA LE,TOYOTA 2013,Silver
3,Priuc C,TOYOTA 2014,White
4,4Runner Limited,TOYOTA 2015,Black
5,Lexus Limited,LEXUS 2016,Blue
'''),
      );

      expect(rows.map((row) => row.title), [
        'TOYOTA 2013',
        'TOYOTA 2014',
        'TOYOTA 2015',
        'LEXUS 2016',
      ]);
      expect(rows.map((row) => row.model), [
        'CROLLA LE',
        'Priuc C',
        '4Runner Limited',
        'Lexus Limited',
      ]);
      expect(rows.first.fields['title'], 'TOYOTA 2013');
      expect(rows.first.fields['model'], 'CROLLA LE');
      expect(rows.first.color, 'Silver');
    },
  );

  test(
    'imports Brand and year and Model into the corresponding poster fields',
    () async {
      final rows = await VehicleListImporter.fromBytes(
        'vehicles.csv',
        utf8.encode('No.,Brand and year,Model\n2,TOYOTA 2013,CROLLA LE\n'),
      );

      expect(rows.single.title, 'TOYOTA 2013');
      expect(rows.single.model, 'CROLLA LE');
    },
  );

  test(
    'combines separate brand and year columns without translating the model',
    () async {
      final rows = await VehicleListImporter.fromBytes(
        'vehicles.csv',
        utf8.encode('No.,Brand,Year,Model\n2,TOYOTA,2013,CROLLA LE\n'),
      );

      expect(rows.single.title, 'TOYOTA 2013');
      expect(rows.single.model, 'CROLLA LE');
    },
  );

  test('a Model column alone stays in the poster model field', () async {
    final rows = await VehicleListImporter.fromBytes(
      'vehicles.csv',
      utf8.encode('No.,Model\n2,CROLLA LE\n'),
    );

    expect(rows.single.title, isEmpty);
    expect(rows.single.model, 'CROLLA LE');
  });
}

String _worksheet(List<List<String>> rows, {bool prefixed = false}) {
  final prefix = prefixed ? 'x:' : '';
  final namespace = prefixed
      ? ' xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
      : ' xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"';
  final buffer = StringBuffer(
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<${prefix}worksheet$namespace>'
    '<${prefix}sheetData>',
  );
  for (var rowIndex = 0; rowIndex < rows.length; rowIndex++) {
    final rowNumber = rowIndex + 1;
    buffer.write('<${prefix}row r="$rowNumber">');
    for (
      var columnIndex = 0;
      columnIndex < rows[rowIndex].length;
      columnIndex++
    ) {
      final address = '${String.fromCharCode(65 + columnIndex)}$rowNumber';
      final value = rows[rowIndex][columnIndex]
          .replaceAll('&', '&amp;')
          .replaceAll('<', '&lt;')
          .replaceAll('>', '&gt;');
      buffer.write(
        '<${prefix}c r="$address" t="str"><${prefix}v>$value</${prefix}v></${prefix}c>',
      );
    }
    buffer.write('</${prefix}row>');
  }
  return '$buffer</${prefix}sheetData></${prefix}worksheet>';
}
